### ISSUE TITLE
General user experience issues

### ISSUE THREAD

**Issue by dangom** [vzaccaria/pandoc-mm#2]
Hi there again,

I noticed some small annoyances with the current state of pandoc-mm, and I figured I'd might as well report them.
- It won't work if any of `#TITLE, #AUTHOR or #COLUMNS` is unset, throwing the following misleading message:

> pandoc-mm: Sorry, the document should begin with at least one top concept
- It won't parse :PROPERTIES: if there is an empty line on it.
  In the following example, both color and placement are ignored:

```
:PROPERTIES:
:color: red

:placement: VV
:END:
```
- It depends on the font family "Fira Sans" to be installed on the system. If these fonts are missing the tool will work anyway, but the output won't contain any text.
- The user has to be aware of placement distances to avoid text overlapping. 
  Placement distance (or placement altogether) could probably be abstracted away from user responsibility. This is particularly annoying when adding new mind map entries - which causes all previous positioning to break.
  Example: 
  Try adding the following line to to example given in the README to see text overlaps:
  `* TEST`
- There is a maximum number of sieblings, namely 4. More than that and they'll be overwritten.
  Try adding the following lines to to example given in the README to see the effect:

```
*TEST1
*TEST4
*TEST3
*TEST4
```

Unfortunately I'm not familiar with Haskell, otherwise I'd try and contribute with a PR.
In any case, this is a really cool tool, so thanks for it.

**Comment by vzaccaria** [comment]
Thanks for pointing that out. I am splitting this issue into several so that I can address them.

**Comment by vzaccaria** [comment]
ok, closing this as I created single issue points
